on: 
  workflow_dispatch:
    inputs:
      name:
          description: "Hema"
          required: true
      environment:
           description: choose envir
           required: true
           type: choice
           options:
             - dev
             - test
             - prod
jobs:
  test:
     runs-on: ubuntu-latest
     steps:
       - run: echo Hello ${{ github.event.inputs.name }}
